# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SMS-Send-US-TMobile
version:      v0.0.3
version_from: lib/SMS/Send/US/TMobile.pm
installdirs:  site
requires:
    Net::SSLeay:                   0
    SMS::Send::Driver:             0
    Test::More:                    0
    URI::Escape:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
